"use strict";
var utils_1 = require("./utils");
exports.fieldFactory = utils_1.fieldFactory;
exports.tempFactory = utils_1.tempFactory;
exports.widgetFactory = utils_1.widgetFactory;
exports.utils = utils_1.utils;
var object_1 = require("./libs/fields/object");
var string_1 = require("./libs/fields/string");
var number_1 = require("./libs/fields/number");
var boolean_1 = require("./libs/fields/boolean");
var array_1 = require("./libs/fields/array");
var none_1 = require("./libs/fields/none");
var default_1 = require("./libs/temps/default");
var row_1 = require("./libs/temps/row");
var col_1 = require("./libs/temps/col");
var formitem_1 = require("./libs/temps/formitem");
var input_1 = require("./libs/widgets/input");
var inputnumber_1 = require("./libs/widgets/inputnumber");
var switch_1 = require("./libs/widgets/switch");
var checkbox_1 = require("./libs/widgets/checkbox");
var select_1 = require("./libs/widgets/select");
var checkboxes_1 = require("./libs/widgets/checkboxes");
var autocomplete_1 = require("./libs/widgets/autocomplete");
var tree_1 = require("./libs/widgets/tree");
var steps_1 = require("./libs/widgets/steps");
var form_1 = require("./libs/form");
exports.SchemaForm = form_1.SchemaForm;
var card_1 = require("./libs/temps/card");
var base_1 = require("./libs/widgets/base");
exports.BaseWidget = base_1.BaseWidget;
var base_2 = require("./libs/fields/base");
exports.BaseField = base_2.BaseField;
var base_3 = require("./libs/temps/base");
exports.BaseTemp = base_3.BaseTemp;
var base_factory_1 = require("./libs/base.factory");
exports.BaseFactory = base_factory_1.BaseFactory;
var merge_1 = require("./libs/core/merge");
exports.mergeSchema = merge_1.mergeSchema;
var form_2 = require("./libs/widgets/form");
utils_1.fieldFactory.add("object", object_1.ObjectField);
utils_1.fieldFactory.add("string", string_1.StringField);
utils_1.fieldFactory.add("text", string_1.StringField);
utils_1.fieldFactory.add("number", number_1.NumberField);
utils_1.fieldFactory.add("boolean", boolean_1.BoolField);
utils_1.fieldFactory.add("array", array_1.ArrayField);
utils_1.fieldFactory.add("none", none_1.NoneField);
utils_1.tempFactory.add("default", default_1.DefaultTemp);
utils_1.tempFactory.add("row", row_1.RowTemp);
utils_1.tempFactory.add("card", card_1.CardTemp);
utils_1.tempFactory.add("col", col_1.ColTemp);
utils_1.tempFactory.add("formitem", formitem_1.FormItemTemp);
utils_1.widgetFactory.add("default", input_1.InputWidget);
utils_1.widgetFactory.add("number", inputnumber_1.InputNumberWidget);
utils_1.widgetFactory.add("checkbox", checkbox_1.CheckboxWidget);
utils_1.widgetFactory.add("switch", switch_1.SwitchWidget);
utils_1.widgetFactory.add("select", select_1.SelectWidget);
utils_1.widgetFactory.add("checkboxes", checkboxes_1.CheckboxesWidget);
utils_1.widgetFactory.add("autocomplete", autocomplete_1.AutoCompleteWidget);
utils_1.widgetFactory.add("tree", tree_1.TreeWidget);
utils_1.widgetFactory.add("steps", steps_1.StepsWidget);
utils_1.widgetFactory.add("form", form_2.FormWidget);
//# sourceMappingURL=index.js.map