"use strict";
const utils_1 = require("./utils");
exports.fieldFactory = utils_1.fieldFactory;
exports.tempFactory = utils_1.tempFactory;
exports.widgetFactory = utils_1.widgetFactory;
const object_1 = require("./libs/fields/object");
const string_1 = require("./libs/fields/string");
const number_1 = require("./libs/fields/number");
const boolean_1 = require("./libs/fields/boolean");
const array_1 = require("./libs/fields/array");
const none_1 = require("./libs/fields/none");
const default_1 = require("./libs/temps/default");
const row_1 = require("./libs/temps/row");
const col_1 = require("./libs/temps/col");
const formitem_1 = require("./libs/temps/formitem");
const array_2 = require("./libs/temps/array");
const input_1 = require("./libs/widgets/input");
const inputnumber_1 = require("./libs/widgets/inputnumber");
const switch_1 = require("./libs/widgets/switch");
const checkbox_1 = require("./libs/widgets/checkbox");
const select_1 = require("./libs/widgets/select");
const checkboxes_1 = require("./libs/widgets/checkboxes");
const autocomplete_1 = require("./libs/widgets/autocomplete");
const tree_1 = require("./libs/widgets/tree");
const steps_1 = require("./libs/widgets/steps");
const form_1 = require("./libs/form");
exports.SchemaForm = form_1.SchemaForm;
utils_1.fieldFactory.add("object", object_1.ObjectField);
utils_1.fieldFactory.add("string", string_1.StringField);
utils_1.fieldFactory.add("text", string_1.StringField);
utils_1.fieldFactory.add("number", number_1.NumberField);
utils_1.fieldFactory.add("boolean", boolean_1.BoolField);
utils_1.fieldFactory.add("array", array_1.ArrayField);
utils_1.fieldFactory.add("none", none_1.NoneField);
utils_1.tempFactory.add("default", default_1.DefaultTemp);
utils_1.tempFactory.add("row", row_1.RowTemp);
utils_1.tempFactory.add("col", col_1.ColTemp);
utils_1.tempFactory.add("formitem", formitem_1.FormItemTemp);
utils_1.tempFactory.add("array", array_2.ArrayTemp);
utils_1.widgetFactory.add("default", input_1.InputWidget);
utils_1.widgetFactory.add("number", inputnumber_1.InputNumberWidget);
utils_1.widgetFactory.add("checkbox", checkbox_1.CheckboxWidget);
utils_1.widgetFactory.add("switch", switch_1.SwitchWidget);
utils_1.widgetFactory.add("select", select_1.SelectWidget);
utils_1.widgetFactory.add("checkboxes", checkboxes_1.CheckboxesWidget);
utils_1.widgetFactory.add("autocomplete", autocomplete_1.AutoCompleteWidget);
utils_1.widgetFactory.add("tree", tree_1.TreeWidget);
utils_1.widgetFactory.add("steps", steps_1.StepsWidget);
//# sourceMappingURL=index.js.map